# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: books.proto for package 'proto'

require 'grpc'
require 'books_pb'

module Proto
  module Books
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Books'

      rpc :GetBook, GetBookRequest, GetBookResponse
      rpc :GetBooks, GetBooksRequest, GetBooksResponse
      rpc :CreateBook, CreateBookRequest, CreateBookResponse
      rpc :UpdateBook, UpdateBookRequest, UpdateBookResponse
      rpc :DeleteBook, DeleteBookRequest, DeleteBookResponse
    end

    Stub = Service.rpc_stub_class
  end
end
