# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("books.proto", :syntax => :proto3) do
    add_message "proto.Book" do
      optional :id, :int32, 1
      optional :title, :string, 2
      optional :pages, :int32, 3
      optional :author_id, :int32, 4
    end
    add_message "proto.GetBookRequest" do
      optional :book_id, :int32, 1
    end
    add_message "proto.GetBookResponse" do
      optional :book, :message, 1, "proto.Book"
    end
    add_message "proto.GetBooksRequest" do
      optional :author_id, :int32, 1
      optional :order, :string, 2
    end
    add_message "proto.GetBooksResponse" do
      repeated :books, :message, 1, "proto.Book"
    end
    add_message "proto.CreateBookRequest" do
      optional :title, :string, 1
      optional :pages, :int32, 2
      optional :author_id, :int32, 3
    end
    add_message "proto.CreateBookResponse" do
      optional :book, :message, 1, "proto.Book"
    end
    add_message "proto.UpdateBookRequest" do
      optional :book, :message, 1, "proto.Book"
    end
    add_message "proto.UpdateBookResponse" do
    end
    add_message "proto.DeleteBookRequest" do
      optional :book_id, :int32, 1
    end
    add_message "proto.DeleteBookResponse" do
    end
  end
end

module Proto
  Book = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Book").msgclass
  GetBookRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetBookRequest").msgclass
  GetBookResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetBookResponse").msgclass
  GetBooksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetBooksRequest").msgclass
  GetBooksResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetBooksResponse").msgclass
  CreateBookRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CreateBookRequest").msgclass
  CreateBookResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.CreateBookResponse").msgclass
  UpdateBookRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UpdateBookRequest").msgclass
  UpdateBookResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.UpdateBookResponse").msgclass
  DeleteBookRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DeleteBookRequest").msgclass
  DeleteBookResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.DeleteBookResponse").msgclass
end
